language: bash

matrix:
  include:
    - os: linux
      dist: trusty
    - os: linux
      dist: xenial
    - os: linux
      dist: zesty
    

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install shellcheck ; fi

install: true
script:
- shellcheck ./goinstall.sh || travis_terminate 1
- ./goinstall.sh --64 || travis_terminate 1
- ./tests/main.sh
